name: Build Releases
on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      #fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf
          - armv5te-unknown-linux-gnueabi
          - armv5te-unknown-linux-musleabi
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          #- i586-unknown-linux-gnu
          #- i586-unknown-linux-musl
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - mipsel-unknown-linux-gnu
          - mipsel-unknown-linux-musl
          #- #powerpc-unknown-linux-gnu
          #- #thumbv7neon-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        if: env.test == 'true'
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: target/${{ matrix.target }}/release/{tonels,tonelc}
          strip: false
          args: --best -9

      - name: Compress
        run: |
          cd target/${{ matrix.target }}/release
          zip tonel_${{ matrix.target }}.zip tonelc tonels

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}

  build-macos:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      #fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          #- aarch64-apple-ios-sim
          #- aarch64-apple-ios
          - x86_64-apple-darwin
          #- x86_64-apple-ios

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: target/${{ matrix.target }}/release/{tonels,tonelc}
          strip: false
          args: --best -9

      - name: Compress
        run: |
          cd target/${{ matrix.target }}/release
          zip tonel_${{ matrix.target }}.zip tonelc tonels

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}
