name: Rust

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
